# Replaced with content of:
# https://docs.docker.com/samples/rails/#connect-the-database
# TODO: Refactor database.yml to be injected via docker-compose
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: friend_list_on_rails_development


test:
  <<: *default
  database: friend_list_on_rails_test
